apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: doumbouya/manager:latest
          ports:
            - containerPort: 8761
