apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: doumbouya/player-service:latest
          ports:
            - containerPort: 8012
