apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stats-service
  template:
    metadata:
      labels:
        app: stats-service
    spec:
      containers:
        - name: stats-service
          image: doumbouya/stats-service:latest
          ports:
            - containerPort: 8014  
