apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
        - name: team-service
          image: doumbouya/team-service:latest
          ports:
            - containerPort: 8011
